version: '3'

networks:
  api-tests:
    driver: bridge

services:
  api_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    depends_on:
      - db
    volumes:
      - $PWD:/go/src/github.com/pennsieve/model-service-serverless/api
    networks:
      - api-tests
  db:
    image: neo4j/neo4j-arm64-experimental:3.5.30
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/neo4jPassword
    restart: on-failure
    networks:
      - api-tests